### ISSUE TITLE
Window layout different

### ISSUE THREAD

**Issue by akshit-sharma** [Dhanus3133/Leetbuddy.nvim#10]
I opened nvim followed by `:LBQuestions` followed by selecting any question.
On my nvim, the input.txt opened on the left and right side is divided into executable on top and code window on the bottom.

Do I need to set something explicitly?

My init file has:
```
    use {
      'Dhanus3133/Leetbuddy.nvim',
      requires = {
        'nvim-lua/plenary.nvim',
        'nvim-telescope/telescope.nvim',
      },
      config = function()
        require('leetbuddy').setup({
          domain = "com",
          language = "cpp",
        })
      end,
    }
```

Thanks

![image](https://github.com/Dhanus3133/Leetbuddy.nvim/assets/2051760/c36e4fdb-d880-408b-b7b5-f253e3ac8f55)

**Comment by Dhanus3133** [comment]
This is due to the default way of splitting windows in Vim. By changing the options [`splitright`](https://neovim.io/doc/user/options.html#'splitright') and [`splitbelow`](https://neovim.io/doc/user/options.html#'splitbelow') to `true`, you can help resolve the problem.
