### ISSUE TITLE
Wrong window split, fixed.

### ISSUE THREAD

**Issue by JulesHauchecorne** [Dhanus3133/Leetbuddy.nvim#11]
When I started leetbuddy the coding window ended up being the small bottom right one and the input one being the largest one taking half the screen on the left. 
Fixed it by adding this line in the split.lua:31 file to rotate the window after the first v split and before the second split. 
    vim.cmd("wincmd x")

**Comment by Dhanus3133** [comment]
The issue has been fixed.
