### ISSUE TITLE
Starter code not loading

### ISSUE THREAD

**Issue by akshit-sharma** [Dhanus3133/Leetbuddy.nvim#13]
I am the following configuration:
```
require('leetbuddy').setup({
domain = "com",
language = "cpp",
})
```

While loading some questions (tested for 1000, 1071, 1072), the starter code buffer is empty.
It works for others such as (1, 2, 1005) the code buffer has starter code.

Why would this be happening?

**Comment by Dhanus3133** [comment]
Try using `:LBReset` command from the code buffer to reset the template.

**Comment by akshit-sharma** [comment]
Thanks, that makes it works.
