### ISSUE TITLE
Wrong credentials, how to reset?

### ISSUE THREAD

**Issue by einKnuffy** [Dhanus3133/Leetbuddy.nvim#14]
As stated above.

**Comment by Dhanus3133** [comment]
It does automatically validate your credentials whenever you initialize the plugin in a new session. Incase, If it doesn't you can remove a file generated by leetbuddy called `.lbcookie` which will be located in:
- Linux or Mac: `~/` which is the `/home/<user>/`  
- Windows: `C:\Users\<user>`
