### ISSUE TITLE
Post request fails to write

### ISSUE THREAD

**Issue by Rpyaanng** [Dhanus3133/Leetbuddy.nvim#16]
I get this whenever I try to sign in, I think it's a permission issue but I haven't been able to resolve it yet, any help would be appreciated.

`Error executing luv callback:
....local/share/nvim/lazy/plenary.nvim/lua/plenary/curl.lua:274: post leetcode.com/graphql - curl error exit_code=23 stderr={ "curl: (23) Failed writing received data to disk/application" }
stack traceback:
        [C]: in function 'error'
        ....local/share/nvim/lazy/plenary.nvim/lua/plenary/curl.lua:274: in function '_user_on_exit'
        .../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:239: in function '_shutdown'
        .../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:46: in function <.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:37>
        [C]: in function 'wait'
        .../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:485: in function 'wait'
        .../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:452: in function 'sync'
        ....local/share/nvim/lazy/plenary.nvim/lua/plenary/curl.lua:292: in function 'post'
        ...share/nvim/lazy/LeetBuddy.nvim/lua/leetbuddy/cookies.lua:75: in function <...share/nvim/lazy/LeetBuddy.nvim/lua/leetbuddy/cookies.lua:49>
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        ...are/nvim/lazy/LeetBuddy.nvim/lua/leetbuddy/questions.lua:160: in function <...are/nvim/lazy/LeetBuddy.nvim/lua/leetbuddy/questions.lua:159>`

**Comment by Dhanus3133** [comment]
I believe the issue is due to cURL library. Try checking if it is available in your system (If not sync your distro with latest packages) and then try some basic cURL POST request using the terminal.

**Comment by Rpyaanng** [comment]
Sorry I got it to work, I was using Ubuntu 20.04 but after upgrading to 22.04 it started working.
