### ISSUE TITLE
Filter by difficulty

### ISSUE THREAD

**Issue by yamiteru** [Dhanus3133/Leetbuddy.nvim#18]
Hi! First of all I want to say thank you for this plugin.

However my current flow looks like this:
- Open browser
- Open leetcode
- Search by difficulty (and maybe other params)
- Find a problem I like
- Open terminal
- Open Nvim
- Paste the name of the problem into your plugin
- Start solving the problem

I'd like to simplify it as follows:
- Open terminal
- Open Nvim
- Search/filter problem
- Find problem I like
- Start solving the problem

**Comment by Dhanus3133** [comment]
Done, check the readme for shortcuts
