### ISSUE TITLE
Tests not working

### ISSUE THREAD

**Issue by einKnuffy** [Dhanus3133/Leetbuddy.nvim#20]
Hello, I was extremely happy that I seemingly finally set up Leetbuddy.
But now after writing some test code for a problem and running `:LBTest`, I do not receive any response even after like 5 minutes or so and only the green text saying Executing.... is visible. In the background it must be still loading with curl or so.. cause I can not do anything else - neovim quite much freezes.

![grafik](https://github.com/Dhanus3133/Leetbuddy.nvim/assets/66639485/cc564fe9-81a4-4489-a6c7-a5ab7982f284)

**Comment by Dhanus3133** [comment]
Just added a debug flag where you make it as true in your config and try `LBTest` and send the response shown in the `:messages`

**Comment by ahmed-alahmadi** [comment]
I have more or less a similar issue although it isn't frozen but i get the following error

"Error executing Lua callback: .../share/nvim/lazy/LeetBuddy.nvim/lua/leetbuddy/runner.lua:60: Expected value but found invalid token at character 2
stack traceback:
	[C]: in function 'decode'
	.../share/nvim/lazy/LeetBuddy.nvim/lua/leetbuddy/runner.lua:60: in function 'generate_id'
	.../share/nvim/lazy/LeetBuddy.nvim/lua/leetbuddy/runner.lua:102: in function 'run'
	.../share/nvim/lazy/LeetBuddy.nvim/lua/leetbuddy/runner.lua:113: in function <.../share/nvim/lazy/LeetBuddy.nvim"
	
i get a similar issue for submit as well.

**Comment by mixtli** [comment]
Same issue here.  Added some debugging and I'm getting a 403 and a bunch of html telling me my csrf token is invalid.  I'm not sure how to log out and try again.   Should there be an explicit mechanism to logout and login?

**Comment by mixtli** [comment]
I remove .lbcookie and tried again with a new session id and csrf token from the web inspector and still got the same thing.  Think this thing is broken.

**Comment by Dhanus3133** [comment]
Can someone share the `:messages` logs with `debug = true` config

**Comment by ahmed-alahmadi** [comment]
sorry for the late reply, but as @mixtli mentioned i get 403 with debug on

**Comment by Dhanus3133** [comment]
Seems like the csrf token is not a valid. Can you try logging into the leetcode in a private/incognito browser and then copy the session and csrf token from there.

**Comment by ahmed-alahmadi** [comment]
Unfortunately, i still get the same issue. Let me know if you need more details.

**Comment by Dhanus3133** [comment]
Share the logs.

**Comment by andrescuco** [comment]
What @efren-yuen mentioned worked for me, I went to leetcode.com and submitted a random question, then when I tried again on leetbuddy it started working.

**Comment by Dhanus3133** [comment]
Great! Closing the issue.
