### ISSUE TITLE
input.txt shows only one test case

### ISSUE THREAD

**Issue by 3seoksw** [Dhanus3133/Leetbuddy.nvim#22]
Everything works fine except for the `input.txt`.
It only shows one test case and runs one test with the one that is in the `input.txt`.

Is there something I've missed setting up? 
BTW, thanks a lot for such a plugin. 

<img width="1224" alt="Screenshot 2023-08-14 at 8 22 21 PM" src="https://github.com/Dhanus3133/Leetbuddy.nvim/assets/97219959/c0b02147-e302-46a5-8fd4-0afe369e749f">
Pass
<img width="1225" alt="Screenshot 2023-08-14 at 8 25 45 PM" src="https://github.com/Dhanus3133/Leetbuddy.nvim/assets/97219959/160298b5-00c3-43e9-b8d3-5e62d55c36c3">
Fail

**Comment by Dhanus3133** [comment]
You can add multiple test cases continuously in your inputs.txt like for example if you need to add 2nd test case, it looks like this
```
[2,7,11,15]
9
[3,2,4]
6
```
Now, when running `:LBTest` it runs the two test cases. To submit the code use `LBSubmit`.

**Comment by 3seoksw** [comment]
Oh, so for the multiple test cases, I need to add them manually? I thought the test cases from the question were to be added to input.txt automatically 😂
Thanks for the help and for the great work 👍🏼

**Comment by 3seoksw** [comment]
Oh, so for the multiple test cases, I need to add them manually? I thought the test cases from the question were to be added to input.txt automatically 😂
Thanks for the help and for the great work 👍🏼
