### ISSUE TITLE
suggest and some question

### ISSUE THREAD

**Issue by bsv-khoavo** [Dhanus3133/Leetbuddy.nvim#27]
1. suggest
I looked the video and i think the leetcode request ( which info of test) is should'nt pop up it's should more flat with code for read and code is working at sametime.
2. question
- is the data leetcode autoupdate?
- How process is going done? ( any big update or something cause i look your extension is really awesome but i not start leetcode yet just in plan)
3. Thank you and keep it up. Good job guys

**Comment by Dhanus3133** [comment]
1. I understand, maybe a new layout where you can code and read the question together. Will work on this later when I can.
2. It works the same way as how the Leetcode website works. The data are parsed and shown each time from the Leetcode API and All the best on your Leetcode journey.
3. Consider a :star: if you like this plugin :)
