### ISSUE TITLE
How to trigger login?

### ISSUE THREAD

**Issue by kohane27** [Dhanus3133/Leetbuddy.nvim#28]
Hello there. Hope you're doing well. Thank you for creating this plugin. The vim emulator in the official website sucks big time.

However, I have trouble using this plugin. After installing, I don't have the trigger to input the cookie and the CSRF token. I see the `~/.leetcode` directory created but it's empty inside. Can I manually create the file and input the token into the file?

Thank you again!

**Comment by Dhanus3133** [comment]
It is because of the `lazy = true`, You can use `:LBQuestions`, it automatically validates and only asks for cookie details if it isn't able to authenticate. Hope it solves the issue.
