### ISSUE TITLE
Where is the docs?

### ISSUE THREAD

**Issue by nyngwang** [Dhanus3133/Leetbuddy.nvim#3]
What should I do?

![image](https://github.com/Dhanus3133/Leetbuddy.nvim/assets/24765272/69ffe3c7-16aa-4827-9695-169ec4d66446)

**Comment by Dhanus3133** [comment]
Hey, just updated with the [README.md](https://github.com/Dhanus3133/Leetbuddy.nvim#login-to-your-account) follow the process. Thanks :)
