### ISSUE TITLE
Can ony see 20 questions

### ISSUE THREAD

**Issue by arorashivoy** [Dhanus3133/Leetbuddy.nvim#32]
When I do command `:LBQuestions` I can only see 20 questions and not all the other questions.

<img width="1776" alt="image" src="https://github.com/Dhanus3133/Leetbuddy.nvim/assets/85881270/7cc99d0e-781c-47a9-93d5-8349eb339f95">

**Comment by csh0101** [comment]
the same question

**Comment by csh0101** [comment]
I read the lua code. but i'm noob for lua . 
```  lua

local function display_questions(search_query)
	local graphql_endpoint = config.graphql_endpoint

	local variables = {
		limit = 20,
		filters = {
			difficulty = M.difficulty,
			searchKeywords = search_query,
			status = M.status,
		},
	}

	local query = [[
    query problemsetQuestionList($limit: Int, $filters: QuestionListFilterInput) {
  ]] .. (config.domain == "cn" and [[
      problemsetQuestionList(
  ]] or [[
      problemsetQuestionList: questionList(
  ]]) .. [[
        categorySlug: ""
        limit: $limit
        filters: $filters
    ) {
  ]] .. (config.domain == "cn" and [[
          total
          questions {
            paidOnly
            titleCn
            frontendQuestionId
  ]] or [[
          total: totalNum
          questions: data {
            paidOnly: isPaidOnly
            titleCn: title
            frontendQuestionId: questionFrontendId
  ]]) .. [[
            difficulty
            isFavor
            status
            titleSlug
        }
      }
    }
  ]]

```
limit 20 is a hard code for questions query.

in my situation, domain is "cn"..

so the graphql query is this.

``` graphql
query problemsetQuestionList($limit: Int, $filters: QuestionListFilterInput) {
  problemsetQuestionList(
    categorySlug: ""
    limit: $limit
    filters: $filters
  ) {
    total
    questions {
      paidOnly
      titleCn
      frontendQuestionId
      difficulty
      isFavor
      status
      titleSlug
    }
  }
}
```
at the moment, I find we can only find the 1-20 problem..

do you consider add page scroll for this?  a configured page size for every page. maybe it's 20 '30 '50, and user can press shortcut to jump into next page or prev page?  just a little suggessstion.

any way,the simple way for developer is let limit vars can be configured ..

**Comment by csh0101** [comment]
fyi @arorashivoy @Dhanus3133

**Comment by Dhanus3133** [comment]
You can check the README for the keymaps on the paginating problems in Telescope. Also, you can now increase the total number of problems displayed with `limit` in config, the default is 30 now.
