### ISSUE TITLE
Can't List Any Questions with domain cn

### ISSUE THREAD

**Issue by andyli386** [Dhanus3133/Leetbuddy.nvim#4]
Hello, 
this is my configuration in neovim
  {
    "Dhanus3133/LeetBuddy.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim",
    },
    config = function()
      require("leetbuddy").setup({
        language = "py",
        domain = "cn"
      })
    end,

    keys = {
      { "<leader>lq", "<cmd>LBQuestions<cr>", desc = "List Questions" },
      { "<leader>ll", "<cmd>LBQuestion<cr>", desc = "View Question" },
      { "<leader>lr", "<cmd>LBReset<cr>", desc = "Reset Code" },
      { "<leader>lt", "<cmd>LBTest<cr>", desc = "Run Code" },
      { "<leader>ls", "<cmd>LBSubmit<cr>", desc = "Submit Code" },
    },
  }
just add 'domain="cn"', I can login with my account but cannot find any questions when I use <leader>lq command.

**Comment by Dhanus3133** [comment]
The implementation till now I made was focused on global but yet I haven't yet completely added the support for "**cn**". The support for the "**cn**" domain is on my radar, and I will be looking into it soon to make fully compatible with the Chinese Leetcode platform.

**Comment by andyli386** [comment]
Many thanks

**Comment by Dhanus3133** [comment]
Hey @andyli386, The plugin now supports the `cn` version of Leetcode. If you encounter any issues or have suggestions, please let me know. Thanks.

**Comment by meetorion** [comment]
I can use this plugin when setting up the COM version, but the CN version doesn't work.
