### ISSUE TITLE
Is it possible to create windows on a new tabpage instead of overwriting the existing one?

### ISSUE THREAD

**Issue by nyngwang** [Dhanus3133/Leetbuddy.nvim#6]
As title.

After choosing a problem from `LBQuestions` it just replaces the content of the current tabpage. It will be more appropriate to place all those problems related windows on a new tabpage instead. This way people who accidentally call `LBQuestions` won't lose the content of the existing tabpage of Vim.

Thank you.

**Comment by Dhanus3133** [comment]
Hey, If someone called the `LBQuestions` accidentally can now use `:LBClose` command which closes specific tabs opened by Leetbuddy without affecting other opened files. (May not suit well when there are other split windows). Can this method helps?

**Comment by nyngwang** [comment]
> Hey, If someone called the LBQuestions accidentally [...]

and have selected a problem, then the answer is yes: closing tabs created/opened by Leetbuddy will help.

> (May not suit well when there are other split windows)

I believe the user should be responsible for those additional splits inside the same tabpage created by Leetbuddy if they did. (optional, user-friendly suggestion: You can still take care of this by notifying them the tabpage contains windows not created by Leetbuddy :))

Thanks for taking care of my issue!

**Comment by Dhanus3133** [comment]
Thanks for letting me know! :+1:
